### ISSUE TITLE
Add ability to close a program

### ISSUE THREAD

**Issue by tomjohn1028** [solana-labs/governance-ui#1261]
Unlike #242 the goal of this issue is to open a proposal that will close a program and it's buffers. 

Use case: the PSY DAO Council owns an old version of [Serum Remote](https://github.com/mithraiclabs/serum-remote) that points to old Serum. There's been a new version deployed that is owned by the Open Book DEX DAO. All on-chain data is cleaned up in this old version, so the program can be closed with no orphaned data.

**Comment by mschneider** [comment]
Would try to change upgrade authority and then manually close program

**Comment by tomjohn1028** [comment]
Good point! Closing as this meets the needs of the issue
