### ISSUE TITLE
Treasury page render blocked by third party requests

### ISSUE THREAD

**Issue by tomjohn1028** [solana-labs/governance-ui#1342]
It looks like the treasury page is being blocked and hanging because of requests to https://graph.holaplex.com/v1 are not connecting or hanging. This goes on indefinitely until the request stalls.

![Screen Shot 2023-01-11 at 10 22 29 AM](https://user-images.githubusercontent.com/32071703/211887271-ca42205a-0d0a-4982-9650-5dc3d4488267.png)
![Screen Shot 2023-01-11 at 10 22 17 AM](https://user-images.githubusercontent.com/32071703/211887282-aa1fb031-2104-47f8-b3cb-bf976f953953.png)

![Screen Shot 2023-01-11 at 10 25 03 AM](https://user-images.githubusercontent.com/32071703/211887598-59e5a70c-7fec-40a6-8f42-c6817518cd29.png)

**Comment by tomjohn1028** [comment]
Occasionally it resolves after a full minute

![Screen Shot 2023-01-11 at 10 30 16 AM](https://user-images.githubusercontent.com/32071703/211888716-f0074015-8cf0-4343-b66a-6c79802e1f20.png)

**Comment by asktree** [comment]
We don't use holaplex anymore, but this is still an issue (even if not as drastic), so I will leave the issue up.
