### ISSUE TITLE
Could not verify version of supplied programId

### ISSUE THREAD

**Issue by drez** [solana-labs/governance-ui#2420]
Hi!
I tried creating any type of DAO on devnet. It failed with "Could not verify version of supplied programId" in the console. The interface just freezes.

This is happened to me on https://app.realms.today and on local dev.

**Comment by Dellapots** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@drez

**Comment by drez** [comment]
Is this real? Seems scammy "@web.app" ....

**Comment by drez** [comment]
No relevant anymore
