### ISSUE TITLE
Question - how to add logo, website, twitter metadata?

### ISSUE THREAD

**Issue by qrtp** [solana-labs/governance-ui#245]
First off, thanks for making the wizard it works really well! I see many organizations have metadata, but didn't see any options for these items during the creation steps. 

1. How can I add them?
1. Is it possible to update the the organization name?

**Logo on tiles**
![image](https://user-images.githubusercontent.com/21039114/149133922-3afea419-1c17-4c77-8b23-2c20450265e7.png)

**Website / twitter / etc after clicking**
![image](https://user-images.githubusercontent.com/21039114/149134038-c61b48db-8924-41ab-bd20-708ecbd6794b.png)

**Comment by SebastianBor** [comment]
Yes, it's possible. Eventually it's going to be on-chain certified registry but for now it can be done through a PR like this one https://github.com/solana-labs/governance-ui/pull/268

**Comment by qrtp** [comment]
Thanks @SebastianBor, created https://github.com/solana-labs/governance-ui/pull/276 with our entry.
