### ISSUE TITLE
Improved proposal TX failure handling

### ISSUE THREAD

**Issue by tomjohn1028** [solana-labs/governance-ui#554]
Solana's network has been dropping transactions left and right these days. When submitting a proposal that is split into more than one transaction often times the create proposal TX may make it through, but the insert tx/instruction to the proposal fails. 

The create proposal code should help recover or use these accounts.

**Comment by mschneider** [comment]
Recommend to open proposals during europe morning hours, that's my
workaround :)

**Comment by tomjohn1028** [comment]
> Recommend to open proposals during europe morning hours, that's my workaround :)

LMAO will do

**Comment by kuramo01** [comment]
Kindly open this live chat to talk to the customer service directly on your issue https://direct.lc.chat/13898481/
