### ISSUE TITLE
Text overflowing outside of div

### ISSUE THREAD

**Issue by Abusayid693** [solana-labs/governance-ui#669]
Not sure if this is a bug or intentional for testing, but in both cases it better to handle it. 
One possible solution will be add trailing **....** , when text overflows max-width (eg : Solana-is-a-decentra....)

Browser : Safari
System : MacOS 

![Screenshot 2022-05-08 at 6 49 51 AM](https://user-images.githubusercontent.com/35341198/167277853-51d7913e-fae0-46f3-97db-4df9ed310e9a.png)

**Comment by Abusayid693** [comment]
@abrzezinski94 any thought on this

**Comment by abrzezinski94** [comment]
hello thanks for report we should probably just add word-break: break all for that case

**Comment by Abusayid693** [comment]
@abrzezinski94 I am opening a PR for this fix adding `word-break: break`
