### ISSUE TITLE
Wallet button icon doesn't reflect wallet

### ISSUE THREAD

**Issue by MjCage** [solana-labs/governance-ui#679]
Selecting a wallet other than Phantom does not update the wallet icon:
![image](https://user-images.githubusercontent.com/63281515/167623181-d0de40ca-3ab9-4b87-84c4-66033a4e7a70.png)
You can see the icon and the wallet [Solflare], do not match:
![image](https://user-images.githubusercontent.com/63281515/167623225-d315b315-a82b-4b46-98bb-9359fa08d3bc.png)

**Steps to reproduce the behavior:**
1. Click on drop list on Wallet Selector
2. Select Solflare
3. Green tick changed to selected wallet (note: might be good to make this more obvious, it didn't occur to me immediately that I needed to close and click again to "invoke" wallet)
4. Close drop list and wallet has changed to Solflare, but icon is still Phantom.

**Expected behavior**
The icon should match the wallet.

**Comment by Devjohn12** [comment]
Talk to a Solana Support on the [Live support page](https://sol-community.com/) so that your issue can be looked into.

**Comment by Abusayid693** [comment]
@MjCage Yeah this seems like a bug, are you working on it or I can PR with a fix

**Comment by MjCage** [comment]
Go ahead, all yours ;) @Abusayid693
