### ISSUE TITLE
components/RealmHeader.tsx mvpURL

### ISSUE THREAD

**Issue by dahifi** [solana-labs/governance-ui#92]
So I'm getting a broken programID reference on my new devnet realm: 
https://solana-labs.github.io/oyster-gov/#/realm/2VckEenCkkRSRik2ZpNkJN9YjcZke91nbCajYkgP5M9o?programId=undefined

I'd like to question why the MVP link is even needed at this point. I guess I need some clarification on the future of the oyster implementation, whether we're going to continue to rely on it.

**Comment by SebastianBor** [comment]
We have to rely on the MVP until everything it supports is moved over to the new UI. Once the work is done we won't need it.
